{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNTsy1ug/ysD7BfcH86N0TR",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/katarzynali/kurs-git-1/blob/main/main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Kurs specjalistyczny\n",
        "\n",
        "Programowanie obiektowe\n",
        "w języku\n",
        "Python\n",
        "\n",
        "Każdy z uczestników wybiera jedno zadanie, do którego się przypisuje, tworząc komentarz na nazwie zadania o treści Imię Naziwkso.\n",
        "Zadanie należy oddać w jednym pliku, plik nazywamy main.py.\n",
        "Na początku pliku znajduje się treść zadania oraz krótki opis jak problem został rozwiązany,\n",
        "Zadanie będzie uruchamiane z użyciem Pythona w wersji 3.11.x w następujący sposób python main.py, jeżeli nie będzie błędów, przechodzę do poprawności działania, a następnie kodu,\n",
        "Kod musi zawierać komentarze,\n",
        "Wszelkie pytania dotyczące zadań umieszczamy w komentarzach przy zadaniu,\n",
        "Zadanie wybieramy raz, nie ma możliwości zmiany zadania (w dokumencie jest historia zmian).\n",
        "Nieprzekraczalny termin oddania zadań to 30.11.2025,\n",
        "Wyniki otrzymacie Państwo do 31.12.2025,\n",
        "Zadania wysyłamy na adres: marcin.jasinski@byd.pl w tytule wpisując KS - OOP - 2025 - [temat zadania].\n",
        "\n",
        "Życzę powodzenia.\n",
        "\n"
      ],
      "metadata": {
        "id": "DyTOkuTxvBA-"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2SC3hemho0lM",
        "outputId": "179deeb4-2e2c-404f-961f-10504365a525"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "======================================================================\n",
            "**Witaj w ZOO:** ZOO WROCŁAW \n",
            "======================================================================\n",
            "\n",
            "### Pawilony i ich mieszkańcy:\n",
            "------------------------------\n",
            "**Pawilon:** Sawanna\n",
            "Liczba mieszkańców: 2\n",
            "Nazwy zwierząt: Simba, Nadira\n",
            "------------------------------\n",
            "**Pawilon:** Woliera i Wody\n",
            "Liczba mieszkańców: 2\n",
            "Nazwy zwierząt: Ares, Fraczek\n",
            "\n",
            "### Szczegółowy spis zwierząt:\n",
            "  - Imię: Simba, Gatunek: Lew afrykański, Wiek: 10 lat, Pawilon: Sawanna, Długość ciąży: 110, Młodych w miocie: 3\n",
            "  - Imię: Nadira, Gatunek: Żyrafa, Wiek: 5 lat, Pawilon: Sawanna, Długość ciąży: 457, Młodych w miocie: 1\n",
            "  - Imię: Ares, Gatunek: Orzeł bielik, Wiek: 7 lat, Pawilon: Woliera i Wody, Rozpiętość skrzydeł: 2.40 m, Potrafi latać: Tak\n",
            "  - Imię: Fraczek, Gatunek: Pingwin cesarski, Wiek: 3 lat, Pawilon: Woliera i Wody, Rozpiętość skrzydeł: 0.90 m, Potrafi latać: Nie\n",
            "\n",
            "### Statystyki Zoo:\n",
            "Całkowita liczba zwierząt: **4**\n",
            "Średni wiek wszystkich zwierząt: **6.25 lat**\n",
            "Liczba unikalnych gatunków: **4**\n",
            "======================================================================\n"
          ]
        }
      ],
      "source": [
        "# Klasa bazowa reprezentująca Istotę Żywą (zwierzęta)\n",
        "class IstotaŻywa:\n",
        "    def __init__(self, imie, gatunek, wiek):\n",
        "        # Sprawdzanie poprawności danych\n",
        "        if not isinstance(wiek, int) or wiek < 0:\n",
        "            raise ValueError(\"Wiek musi być nieujemną liczbą całkowitą.\")\n",
        "\n",
        "        self.imie = imie\n",
        "        self.gatunek = gatunek\n",
        "        self.wiek = wiek\n",
        "        self.pawilon = None  # Początkowo zwierzę nie jest przypisane do pawilonu\n",
        "\n",
        "\n",
        "    def przypisz_pawilon(self, nazwa_pawilonu):\n",
        "        # Metoda ustawiająca nazwę pawilonu\n",
        "        self.pawilon = nazwa_pawilonu\n",
        "\n",
        "    def opis(self):\n",
        "        # Metoda zwracająca podstawowy opis zwierzęcia\n",
        "        pawilon_info = self.pawilon if self.pawilon else \"nieznany\"\n",
        "        return (f\"Imię: {self.imie}, Gatunek: {self.gatunek}, Wiek: {self.wiek} lat, Pawilon: {pawilon_info}\")\n",
        "\n",
        "# Klasa Ssak (dziedziczy po IstotaŻywa)\n",
        "class Ssak(IstotaŻywa):\n",
        "    def __init__(self, imie, gatunek, wiek, dlugosc_ciazy, liczba_mlodych):\n",
        "        super().__init__(imie, gatunek, wiek)\n",
        "\n",
        "        if not all(isinstance(val, int) and val >= 0 for val in [dlugosc_ciazy, liczba_mlodych]):\n",
        "            raise ValueError(\"Długość ciąży i liczba młodych muszą być nieujemnymi liczbami całkowitymi.\")\n",
        "\n",
        "        self.dlugosc_ciazy = dlugosc_ciazy  # w dniach/miesiącach\n",
        "        self.liczba_mlodych = liczba_mlodych\n",
        "\n",
        "    def opis(self):\n",
        "        podstawowy_opis = super().opis()\n",
        "        # Wywołanie metody opis z klasy nadrzędnej (IstotaŻywa) i zapisanie jej wyniku\n",
        "        return (f\"{podstawowy_opis}, Długość ciąży: {self.dlugosc_ciazy}, Młodych w miocie: {self.liczba_mlodych}\")\n",
        "\n",
        "# Klasa Ptak (dziedziczy po IstotaŻywa)\n",
        "class Ptak(IstotaŻywa):\n",
        "    def __init__(self, imie, gatunek, wiek, rozpietosc_skrzydel, potrafi_latac):\n",
        "        super().__init__(imie, gatunek, wiek)\n",
        "\n",
        "        if not isinstance(rozpietosc_skrzydel, (int, float)) or rozpietosc_skrzydel < 0:\n",
        "            # Sprawdzenie, czy rozpiętość skrzydeł jest nieujemną liczbą (całkowitą lub zmiennoprzecinkową)\n",
        "            raise ValueError(\"Rozpiętość skrzydeł musi być nieujemną liczbą.\")\n",
        "\n",
        "        if not isinstance(potrafi_latac, bool):\n",
        "            # Sprawdzenie, czy potrafi_latac jest wartością logiczną (True/False)\n",
        "            raise ValueError(\"Potrafi latać musi być wartością logiczną (True/False).\")\n",
        "\n",
        "        self.rozpietosc_skrzydel = rozpietosc_skrzydel  # w metrach\n",
        "        self.potrafi_latac = potrafi_latac\n",
        "\n",
        "\n",
        "    def opis(self):\n",
        "        podstawowy_opis = super().opis()\n",
        "        lotnosc = \"Tak\" if self.potrafi_latac else \"Nie\"\n",
        "        # Ustalenie tekstu \"Tak\" lub \"Nie\" na podstawie wartości logicznej potrafi_latac\n",
        "        return (f\"{podstawowy_opis}, Rozpiętość skrzydeł: {self.rozpietosc_skrzydel:.2f} m, Potrafi latać: {lotnosc}\")\n",
        "\n",
        "# Klasa reprezentująca Pawilon w Zoo\n",
        "class Pawilon:\n",
        "    def __init__(self, nazwa):\n",
        "        self.nazwa = nazwa\n",
        "        self.zwierzeta = []  # Lista przechowująca obiekty zwierząt\n",
        "\n",
        "    def dodaj_zwierze(self, zwierze):\n",
        "        if isinstance(zwierze, IstotaŻywa):\n",
        "            self.zwierzeta.append(zwierze)\n",
        "            # Dodanie obiektu zwierzęcia do listy zwierząt w pawilonie\n",
        "            zwierze.przypisz_pawilon(self.nazwa)\n",
        "        else:\n",
        "            print(f\"Błąd: Obiekt {zwierze} nie jest poprawną Istotą Żywą.\")\n",
        "\n",
        "    def opis(self):\n",
        "        nazwy_zwierzat = [z.imie for z in self.zwierzeta]\n",
        "        # Tworzenie listy imion wszystkich zwierząt w pawilonie\n",
        "        liczba_mieszkancow = len(self.zwierzeta)\n",
        "        # Obliczenie liczby zwierząt w pawilonie\n",
        "\n",
        "        return (\n",
        "            f\"**Pawilon:** {self.nazwa}\\n\"\n",
        "            f\"Liczba mieszkańców: {liczba_mieszkancow}\\n\"\n",
        "            f\"Nazwy zwierząt: {', '.join(nazwy_zwierzat) if nazwy_zwierzat else 'Brak'}\"\n",
        "                )\n",
        "\n",
        "# Klasa reprezentująca całe Zoo (centralny zarządca)\n",
        "class Zoo:\n",
        "    def __init__(self, nazwa):\n",
        "        self.nazwa = nazwa\n",
        "        self.pawilony = {}  # Słownik: {nazwa_pawilonu: obiekt_pawilonu}\n",
        "\n",
        "    def dodaj_pawilon(self, pawilon):\n",
        "        if isinstance(pawilon, Pawilon):\n",
        "            # Sprawdzenie, czy obiekt jest instancją klasy Pawilon\n",
        "            self.pawilony[pawilon.nazwa] = pawilon\n",
        "            # Dodanie obiektu Pawilon do słownika\n",
        "        else:\n",
        "            print(f\"Błąd: Obiekt {pawilon} nie jest instancją klasy Pawilon.\")\n",
        "\n",
        "    def _pobierz_wszystkie_zwierzeta(self):\n",
        "          wszystkie_zwierzeta = []\n",
        "\n",
        "          for pawilon in self.pawilony.values():\n",
        "            wszystkie_zwierzeta.extend(pawilon.zwierzeta)\n",
        "          return wszystkie_zwierzeta\n",
        "\n",
        "    def oblicz_ogolna_liczbe_zwierzat(self):\n",
        "\n",
        "        return len(self._pobierz_wszystkie_zwierzeta())\n",
        "\n",
        "\n",
        "    def oblicz_sredni_wiek(self):\n",
        "        zwierzeta = self._pobierz_wszystkie_zwierzeta()\n",
        "\n",
        "        if not zwierzeta:\n",
        "            # Sprawdzenie, czy lista zwierząt jest pusta\n",
        "            return 0\n",
        "\n",
        "        suma_wieku = sum(z.wiek for z in zwierzeta)\n",
        "        # Obliczenie sumy wieku wszystkich zwierząt\n",
        "        return suma_wieku / len(zwierzeta)\n",
        "\n",
        "    def oblicz_liczbe_gatunkow(self):\n",
        "        zwierzeta = self._pobierz_wszystkie_zwierzeta()\n",
        "        gatunki = {z.gatunek for z in zwierzeta}\n",
        "        # Utworzenie zbioru nazw gatunków\n",
        "        return len(gatunki)\n",
        "\n",
        "\n",
        "    def opis_zoo(self):\n",
        "        print(\"=\" * 70)\n",
        "        print(f\"**Witaj w ZOO:** {self.nazwa.upper()} \")\n",
        "        print(\"=\" * 70)\n",
        "\n",
        "\n",
        "        # Opis pawilonów\n",
        "        print(\"\\n### Pawilony i ich mieszkańcy:\")\n",
        "        if not self.pawilony:\n",
        "            # Sprawdzenie, czy słownik pawilonów jest pusty\n",
        "            print(\"Zoo nie posiada jeszcze żadnych pawilonów.\")\n",
        "        else:\n",
        "            for pawilon in self.pawilony.values():\n",
        "                print(\"-\" * 30)\n",
        "                print(pawilon.opis())\n",
        "\n",
        "\n",
        "        # Szczegółowy opis zwierząt (polimorfizm)\n",
        "        print(\"\\n### Szczegółowy spis zwierząt:\")\n",
        "        wszystkie_zwierzeta = self._pobierz_wszystkie_zwierzeta()\n",
        "        for z in wszystkie_zwierzeta:\n",
        "            print(f\"  - {z.opis()}\")\n",
        "\n",
        "\n",
        "        # Statystyki Zoo\n",
        "        print(\"\\n### Statystyki Zoo:\")\n",
        "        print(f\"Całkowita liczba zwierząt: **{self.oblicz_ogolna_liczbe_zwierzat()}**\")\n",
        "        print(f\"Średni wiek wszystkich zwierząt: **{self.oblicz_sredni_wiek():.2f} lat**\")\n",
        "        print(f\"Liczba unikalnych gatunków: **{self.oblicz_liczbe_gatunkow()}**\")\n",
        "        print(\"=\" * 70)\n",
        "\n",
        "\n",
        "\n",
        "#-- Użycie i testowanie --\n",
        "\n",
        "# Tworzenie obiektów zwierząt\n",
        "ssak_leo = Ssak(\"Simba\", \"Lew afrykański\", 10, 110, 3)\n",
        "ssak_gina = Ssak(\"Nadira\", \"Żyrafa\", 5, 457, 1)\n",
        "\n",
        "ptak_eagles = Ptak(\"Ares\", \"Orzeł bielik\", 7, 2.4, True)\n",
        "ptak_ping = Ptak(\"Fraczek\", \"Pingwin cesarski\", 3, 0.9, False)\n",
        "\n",
        "# Tworzenie pawilonów\n",
        "pawilon_sawanna = Pawilon(\"Sawanna\")\n",
        "pawilon_woliera = Pawilon(\"Woliera i Wody\")\n",
        "\n",
        "\n",
        "# Dodawanie zwierząt do pawilonów\n",
        "pawilon_sawanna.dodaj_zwierze(ssak_leo)\n",
        "pawilon_sawanna.dodaj_zwierze(ssak_gina)\n",
        "pawilon_woliera.dodaj_zwierze(ptak_eagles)\n",
        "pawilon_woliera.dodaj_zwierze(ptak_ping)\n",
        "\n",
        "\n",
        "# Tworzenie obiektu Zoo\n",
        "moje_zoo = Zoo(\"Zoo Wrocław\")\n",
        "\n",
        "\n",
        "# Dodawanie pawilonów do Zoo\n",
        "\n",
        "moje_zoo.dodaj_pawilon(pawilon_sawanna)\n",
        "moje_zoo.dodaj_pawilon(pawilon_woliera)\n",
        "\n",
        "\n",
        "# Wypisanie opisu całego Zoo\n",
        "moje_zoo.opis_zoo()\n",
        "\n"
      ]
    }
  ]
}