{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPI/zIRWiOHFfy1fx1iBxx3",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/katarzynali/kurs-git-1/blob/main/zoo.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fXpE2esvaYAI",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "1052dc68-b4ce-4326-ab30-d0cfc3f2fe37"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dodano pawilon Sawanna do Zoo.\n",
            "Dodano pawilon Woliera do Zoo.\n",
            "Dodano pawilon Pingwinarium do Zoo.\n",
            "Dodano Simba Lew afrykanski do pawilonu Sawanna.\n",
            "Dodano Nadira Żyrafa do pawilonu Sawanna.\n",
            "Dodano Ares Orzeł bielik do pawilonu Woliera.\n",
            "Dodano Fraczek Pingwin cesarski do pawilonu Pingwinarium.\n",
            "==================================================\n",
            "-----WITAJ W ZOO----- : -----ZOO WROCŁAW-----\n",
            "==================================================\n",
            "\n",
            "##### Pawilony i ich mieszkańcy:\n",
            "----------------------------------------\n",
            " -- Pawilon -- Sawanna\n",
            "Liczba mieszkańców : 2\n",
            "Nazwy zwierząt: Simba,Nadira\n",
            "----------------------------------------\n",
            " -- Pawilon -- Woliera\n",
            "Liczba mieszkańców : 1\n",
            "Nazwy zwierząt: Ares\n",
            "----------------------------------------\n",
            " -- Pawilon -- Pingwinarium\n",
            "Liczba mieszkańców : 1\n",
            "Nazwy zwierząt: Fraczek\n",
            "\n",
            "##### Szczegółowy spis zwierząt:\n",
            " - Imię: Simba, Gatunek: Lew afrykanski, Wiek: 10 lat, Pawilon: Sawanna, Długość ciąży: 110 dni, Ilość mlodych w miocie: 2.\n",
            " - Imię: Nadira, Gatunek: Żyrafa, Wiek: 5 lat, Pawilon: Sawanna, Długość ciąży: 457 dni, Ilość mlodych w miocie: 1.\n",
            " - Imię: Ares, Gatunek: Orzeł bielik, Wiek: 7 lat, Pawilon: Woliera, Rozpiętość skrzydeł: 2.4 m,Potrafi latać: Tak\n",
            " - Imię: Fraczek, Gatunek: Pingwin cesarski, Wiek: 3 lat, Pawilon: Pingwinarium, Rozpiętość skrzydeł: 0.9 m,Potrafi latać: Nie\n",
            "\n",
            "##### Statystyki Zoo:\n",
            " * Całkowita liczba zwierząt: 4.\n",
            " * Średni wiek wszystkich zwierzat: 6.25 lat.\n",
            " * Liczba unikalnych gatunków: 4.\n"
          ]
        }
      ],
      "source": [
        "#Klasa bazowa reprezentująca Istotę Żywą (zwierzęta).\n",
        "class IstotaZywa:\n",
        "    def __init__(self, imie: str, gatunek: str, wiek: int) ->None:\n",
        "        #Sprawdza czy wiek nie jest ujemny\n",
        "        if wiek < 0:\n",
        "            raise ValueError(\"Wiek zwierzęcia nie może być ujemny.\")\n",
        "\n",
        "        self.imie = imie.capitalize() #wyswietli w jednolity sposób.\n",
        "        self.gatunek = gatunek.capitalize()\n",
        "        self.wiek = wiek\n",
        "        self.pawilon = None\n",
        "\n",
        "    def przypisz_pawilon(self, nazwa_pawilonu: str) ->None:\n",
        "        #Przypisuje zwierze do konkrenego pawilonu.\n",
        "        self.pawilon = nazwa_pawilonu\n",
        "\n",
        "    def opis(self) ->str:\n",
        "        #Zwraca podstawowy tekstowy opis zwierzęcia.\n",
        "        pawilon_info = self.pawilon if self.pawilon else \"nieznany\"\n",
        "\n",
        "\n",
        "        return (f\"Imię: {self.imie}, \"\n",
        "                f\"Gatunek: {self.gatunek}, \"\n",
        "                f\"Wiek: {self.wiek} lat, \"\n",
        "                f\"Pawilon: {pawilon_info}\"\n",
        "                )\n",
        "\n",
        "\n",
        "#Klasa Ssak dziedziczy po IstotaZywa.\n",
        "class Ssak(IstotaZywa):\n",
        "    def __init__(self, imie: str, gatunek: str, wiek: int, dlugosc_ciazy: int, liczba_mlodych: int) ->None:\n",
        "        if dlugosc_ciazy < 0:\n",
        "            raise ValueError(\"Dlugosc ciąży nie może być liczbą ujemną\")\n",
        "\n",
        "        if liczba_mlodych < 0:\n",
        "            raise ValueError(\"Liczba młodych nie może być liczbą ujemną\")\n",
        "\n",
        "       #Dodaje dane o rozrodzie\n",
        "        super().__init__(imie, gatunek, wiek)\n",
        "        self.dlugosc_ciazy = dlugosc_ciazy\n",
        "        self.liczba_mlodych = liczba_mlodych\n",
        "\n",
        "\n",
        "    def opis(self) ->str:\n",
        "        #Zwraca pełny opis Ssaka.\n",
        "        podstawowy_opis = super().opis()\n",
        "\n",
        "        return (f\"{podstawowy_opis}, \"\n",
        "                f\"Długość ciąży: {self.dlugosc_ciazy} dni, \"\n",
        "                f\"Ilość mlodych w miocie: {self.liczba_mlodych}.\"\n",
        "                )\n",
        "\n",
        "#Klasa Ptak dziedziczy po IstotaZywa.\n",
        "class Ptak(IstotaZywa):\n",
        "    def __init__(self, imie: str, gatunek: str, wiek: int, rozpietosc_skrzydel: float, potrafi_latac: bool) ->None:\n",
        "        if rozpietosc_skrzydel < 0:\n",
        "            raise ValueError(\"Rozpietość skrzydel nie może być liczbą ujemną.\")\n",
        "\n",
        "        if potrafi_latac is not True and potrafi_latac is not False:\n",
        "            raise ValueError(\"Potrafi latać musi być wartością logiczną(True/False).\")\n",
        "\n",
        "        #Dodaje dane o rozpiętości skrzydeł i locie\n",
        "        super().__init__(imie, gatunek, wiek)\n",
        "        self.rozpietosc_skrzydel = rozpietosc_skrzydel\n",
        "        self.potrafi_latac = potrafi_latac\n",
        "\n",
        "\n",
        "    def opis(self):\n",
        "        #Zwraca pełny opis Ptaka.\n",
        "        podstawowy_opis = super().opis()\n",
        "        lotnosc = \"Tak\" if self.potrafi_latac else \"Nie\"\n",
        "\n",
        "        return (f\"{podstawowy_opis}, \"\n",
        "                f\"Rozpiętość skrzydeł: {self.rozpietosc_skrzydel} m,\"\n",
        "                f\"Potrafi latać: {lotnosc}\"\n",
        "                )\n",
        "\n",
        "class Pawilon:\n",
        "    def __init__(self, nazwa: str) ->None:\n",
        "        #Tworzy nowy Pawilon z nazwą i pustą listą zwierząt.\n",
        "       self.nazwa = nazwa\n",
        "       self.zwierzeta =[]\n",
        "\n",
        "    def dodaj_zwierze(self, zwierze: IstotaZywa) ->None:\n",
        "        #Dodaje zwierzę do listy pawilonu i automatycznie przypisuje mu ten pawilon.\n",
        "        self.zwierzeta.append(zwierze)  #Dodaje zwierze na koniec listy\n",
        "        zwierze.przypisz_pawilon(self.nazwa)\n",
        "        print(f\"Dodano {zwierze.imie} {zwierze.gatunek} do pawilonu {self.nazwa}.\")\n",
        "\n",
        "\n",
        "    def opis(self) ->str:\n",
        "        #Zwraca dane pawilonu.\n",
        "        nazwy_zwierzat = [z.imie for z in self.zwierzeta]\n",
        "        liczba_mieszkancow =len(self.zwierzeta)\n",
        "\n",
        "        return (f\" -- Pawilon -- {self.nazwa}\\n\"\n",
        "                f\"Liczba mieszkańców : {liczba_mieszkancow}\\n\"\n",
        "                f\"Nazwy zwierząt: {','.join(nazwy_zwierzat) if nazwy_zwierzat else 'Brak'}\" #Łączy wszystkie nazwy zwierzat z listy.\n",
        "                )\n",
        "\n",
        "class Zoo:\n",
        "    def __init__(self, nazwa) ->None:\n",
        "        #Tworzy Zoo z nazwą i pustym słownikiem na pawilony.\n",
        "        self.nazwa = nazwa\n",
        "        self.pawilony ={}\n",
        "\n",
        "    def dodaj_pawilon(self, pawilon: Pawilon) ->None:\n",
        "        #Dodaje obiekt Pawilonu do słownika Zoo, jesli nazwa nie jest zajęta.\n",
        "        nazwa_pawilonu = pawilon.nazwa\n",
        "        if nazwa_pawilonu not in self.pawilony:\n",
        "            self.pawilony[nazwa_pawilonu] = pawilon\n",
        "            print(f\"Dodano pawilon {nazwa_pawilonu} do Zoo.\")\n",
        "        else:\n",
        "            print(f\"Pawilon o nazwie {nazwa_pawilonu} juz istnieje.\")\n",
        "\n",
        "\n",
        "    def pobierz_wszystkie_zwierzeta(self) ->list:\n",
        "        #Zwraca listę z wszystkimi zwierzętami w całym Zoo.\n",
        "        wszystkie_zwierzeta =[]\n",
        "\n",
        "        for pawilon in self.pawilony.values(): #Pobiera wszystkie obiekty pawilonu.\n",
        "            wszystkie_zwierzeta.extend(pawilon.zwierzeta) #Wszystkie zwierzęta z danego pawilonu są dodane do listy.\n",
        "        return wszystkie_zwierzeta\n",
        "\n",
        "    def oblicz_ogolna_liczba_zwierzat(self) ->int:\n",
        "        return len(self.pobierz_wszystkie_zwierzeta())\n",
        "\n",
        "    def oblicz_sredni_wiek(self) ->float:\n",
        "        zwierzeta = self.pobierz_wszystkie_zwierzeta()\n",
        "\n",
        "        if not zwierzeta:\n",
        "            return 0.0\n",
        "\n",
        "        suma_wieku = sum(z.wiek for z in zwierzeta)\n",
        "        return suma_wieku / len(zwierzeta) # Sume wieku dzielimy przez całkowitą liczbe zwierząt\n",
        "\n",
        "    def oblicz_liczbe_gatunkow(self) ->int:\n",
        "        zwierzeta = self.pobierz_wszystkie_zwierzeta()\n",
        "        gatunki = {z.gatunek for z in zwierzeta}\n",
        "        return len(gatunki)\n",
        "\n",
        "    def drukuj_raport(self) ->None:\n",
        "        print(\"=\"*50)\n",
        "        print(f\"-----WITAJ W ZOO----- : -----{self.nazwa.upper()}-----\") #Zmienia self.nazwa na wielkie litery\n",
        "        print(\"=\"*50)\n",
        "\n",
        "\n",
        "        print(\"\\n##### Pawilony i ich mieszkańcy:\")\n",
        "        if not self.pawilony:\n",
        "            print(\"Zoo nie posiada jeszcze żadnych pawilonów.\")\n",
        "        else:\n",
        "            for nazwa_pawilonu in self.pawilony:\n",
        "                print(\"-\"*40)\n",
        "                pawilon = self.pawilony[nazwa_pawilonu]\n",
        "                print(pawilon.opis())\n",
        "\n",
        "\n",
        "        print(\"\\n##### Szczegółowy spis zwierząt:\")\n",
        "        wszystkie_zwierzeta = self.pobierz_wszystkie_zwierzeta()\n",
        "        if wszystkie_zwierzeta:\n",
        "            for z in wszystkie_zwierzeta:\n",
        "                print(f\" - {z.opis()}\")\n",
        "        else:\n",
        "            print(\"Brak zwierząt w Zoo\")\n",
        "\n",
        "        print(\"\\n##### Statystyki Zoo:\")\n",
        "        print(f\" * Całkowita liczba zwierząt: {self.oblicz_ogolna_liczba_zwierzat()}.\")\n",
        "        print(f\" * Średni wiek wszystkich zwierzat: {self.oblicz_sredni_wiek():.2f} lat.\")\n",
        "        print(f\" * Liczba unikalnych gatunków: {self.oblicz_liczbe_gatunkow()}.\")\n",
        "\n",
        "\n",
        "#Użycie i testowanie.\n",
        "ssak_leo = Ssak(\"simBa\", \"Lew afrykanski\", 10, 110,2)\n",
        "ssak_gina = Ssak(\"NadirA\", \"Żyrafa\", 5, 457, 1)\n",
        "ptak_eagles = Ptak(\"ARes\", \"Orzeł Bielik\", 7, 2.4, True)\n",
        "ptak_ping = Ptak(\"FracZek\",\"Pingwin cesarski\", 3, 0.9, False)\n",
        "\n",
        "pawilon_sawanna = Pawilon(\"Sawanna\")\n",
        "pawilon_woliera = Pawilon(\"Woliera\")\n",
        "pawilon_pingwinarium = Pawilon(\"Pingwinarium\")\n",
        "\n",
        "moje_zoo = Zoo(\"Zoo Wrocław\")\n",
        "\n",
        "#Dodawanie pawilonu\n",
        "moje_zoo.dodaj_pawilon(pawilon_sawanna)\n",
        "moje_zoo.dodaj_pawilon(pawilon_woliera)\n",
        "moje_zoo.dodaj_pawilon(pawilon_pingwinarium)\n",
        "\n",
        "#Dodawanie zwierząt\n",
        "pawilon_sawanna.dodaj_zwierze(ssak_leo)\n",
        "pawilon_sawanna.dodaj_zwierze(ssak_gina)\n",
        "pawilon_woliera.dodaj_zwierze(ptak_eagles)\n",
        "pawilon_pingwinarium.dodaj_zwierze(ptak_ping)\n",
        "\n",
        "moje_zoo.drukuj_raport()\n",
        "\n"
      ]
    }
  ]
}